//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_CHUYEN_NGHANH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int MaKhachHang { get; set; }
        public string HoVaTen { get; set; }
        public string SoDienThoai { get; set; }
        public string QueQuan { get; set; }
        public string GioiTinh { get; set; }
        public string TenTaiKhoan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
