//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_CHUYEN_NGHANH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phi
    {
        public int MaHoaDon { get; set; }
        public Nullable<decimal> TienPhi { get; set; }
        public Nullable<int> Phong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Phong Phong1 { get; set; }
    }
}
