//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_CHUYEN_NGHANH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongDaDat
    {
        public int MaPhongDaDat { get; set; }
        public int MaKhachHang { get; set; }
        public int MaPhong { get; set; }
        public System.DateTime NgayDat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
